services:
  - type: web
    name: summarizer-agent
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8787
